console.log("CORRECT SERVER.JS IS RUNNING");
require("dotenv").config();
const express = require("express");
const fs = require("fs");
const path = require("path");
const http = require("http");

// Optional Dependencies with Safe Loading
let cors, bcrypt, mongoose, multer, jwt, socketIo, nodemailer, rateLimit;
try { cors = require("cors"); } catch (e) { console.warn("⚠️ cors missing, using default."); }
try { bcrypt = require("bcrypt"); } catch (e) { console.warn("⚠️ bcrypt missing, auth disabled."); }
try { mongoose = require("mongoose"); } catch (e) { console.warn("⚠️ mongoose missing, DB features disabled."); }
try { multer = require("multer"); } catch (e) { console.warn("⚠️ multer missing, file uploads disabled."); }
try { jwt = require("jsonwebtoken"); } catch (e) { console.warn("⚠️ jsonwebtoken missing, JWT auth disabled."); }
try { socketIo = require("socket.io"); } catch (e) { console.warn("⚠️ socket.io missing, websockets disabled."); }
try { nodemailer = require("nodemailer"); } catch (e) { console.warn("⚠️ nodemailer missing, email features disabled."); }
try { rateLimit = require("express-rate-limit"); } catch (e) { console.warn("⚠️ express-rate-limit missing, rate limiting disabled."); }

const crypto = require("crypto");

// Local Modules
const { extractResumeText } = require('./resumeParser');
const aiService = require('./aiService');
const callAI = aiService.callAI ? aiService.callAI : async () => ({ error: "AI Service Unavailable" });

const app = express();
const server = http.createServer(app);
let io;
if (socketIo) {
  io = socketIo(server, { cors: { origin: "*" } });
}
const PORT = process.env.PORT || 3000;

// Middleware
if (cors) app.use(cors());

if (rateLimit) {
  const limiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 10000,
    message: "Too many requests from this IP, please try again later.",
    standardHeaders: false,
    legacyHeaders: false
  });
  app.use(limiter);
}

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Serve Frontend Static Files
app.use(express.static(path.join(__dirname, "public")));

// Uploads Directory
const uploadDir = path.join(__dirname, "uploads");
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}
app.use("/uploads", express.static(uploadDir));

/* ================= DATABASE ================= */
let User, Resume, InterviewAttempt, GeneratedQuestion;

if (mongoose) {
  mongoose.connect(process.env.MONGO_URI || "mongodb://127.0.0.1:27017/aiInterviewDB")
    .then(() => console.log("✅ MongoDB Connected"))
    .catch(err => console.error("❌ MongoDB Connection Error:", err));

  // Schemas
  const userSchema = new mongoose.Schema({
    name: String,
    email: { type: String, unique: true },
    password: String,
    role: String,
    experienceLevel: { type: String, default: "Entry" }, // Entry, Mid, Senior, Lead
    github: { type: String, default: "" },
    linkedin: { type: String, default: "" },
    portfolio: { type: String, default: "" },
    phone: { type: String, default: "" },
    avatar: { type: String, default: "male1" }, // identifier for chosen avatar
    resetPasswordToken: String,
    resetPasswordExpires: Date,
    lastPracticeDate: { type: Date },
    practiceStreak: { type: Number, default: 0 },
    createdAt: { type: Date, default: Date.now }
  });

  const resumeSchema = new mongoose.Schema({
    userEmail: String,
    filename: String,
    extractedText: String,
    analysis: {
      score: Number,
      skills: [String],
      level: String,
      summary: String,
      suggestions: [String],
      questions: [String],
      suitable_jobs: [String],
      skills_to_improve: [String]
    },
    uploadedAt: { type: Date, default: Date.now }
  });

  // NEW: Granular tracking for every question attempted
  const attemptSchema = new mongoose.Schema({
    userEmail: String,
    question: String,
    userAnswer: String,
    aiFeedback: String,
    score: Number, // 0-10
    timeTaken: Number, // In seconds
    category: String, // Technical, Behavioral, System Design
    timestamp: { type: Date, default: Date.now },
    sessionMode: String
  });

  // NEW: Track every single question generated by AI
  const questionSchema = new mongoose.Schema({
    userEmail: String,
    questionText: String,
    category: String,
    sessionMode: String,
    timestamp: { type: Date, default: Date.now }
  });

  User = mongoose.model("User", userSchema);
  Resume = mongoose.model("Resume", resumeSchema);
  InterviewAttempt = mongoose.model("InterviewAttempt", attemptSchema);
  GeneratedQuestion = mongoose.model("GeneratedQuestion", questionSchema);
}

/* ================= ROUTES ================= */

// Middleware for JWT Verification
const verifyToken = (req, res, next) => {
  if (!jwt) return next();
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(" ")[1];
  if (!token) return res.status(403).json({ message: "Token required" });
  jwt.verify(token, process.env.JWT_SECRET || "supersecretjwtkey", (err, decoded) => {
    if (err) return res.status(401).json({ message: "Invalid token" });
    req.user = decoded;
    next();
  });
};

// Auth Routes
if (User && bcrypt) {
  app.post("/register", async (req, res) => {
    console.log("🔥 REGISTER ROUTE HIT");
    console.log("Request Body:", req.body);

    const { name, email, password, role, experienceLevel } = req.body;

    try {
      if (!name || !email || !password) {
        console.log("❌ Missing fields");
        return res.status(400).json({ message: "All fields required" });
      }

      const existingUser = await User.findOne({ email });

      if (existingUser) {
        console.log("❌ User already exists");
        return res.status(409).json({ message: "User exists" });
      }

      const hashedPassword = await bcrypt.hash(password, 10);

      const newUser = new User({
        name,
        email,
        password: hashedPassword,
        role,
        experienceLevel: experienceLevel || "Entry"
      });

      await newUser.save();

      console.log("✅ User saved successfully");

      res.status(201).json({ success: true });

    } catch (e) {
      console.error("🚨 REGISTER ERROR:", e);
      res.status(500).json({
        message: "Registration failed",
        error: e.message
      });
    }
  });


  app.post("/login", async (req, res) => {
    const { email, password } = req.body; // 'email' field now holds either email or username
    try {
      // Find user by email OR name (username)
      const user = await User.findOne({
        $or: [
          { email: email },
          { name: email }
        ]
      });

      if (user && await bcrypt.compare(password, user.password)) {
        let token = null;
        if (jwt) {
          token = jwt.sign({ email: user.email, id: user._id }, process.env.JWT_SECRET || "supersecretjwtkey", { expiresIn: '24h' });
        }
        res.json({
          success: true,
          token: token,
          user: { name: user.name, email: user.email, role: user.role, experienceLevel: user.experienceLevel, avatar: user.avatar }
        });
      } else {
        res.status(401).json({ success: false, message: "Invalid credentials" });
      }
    } catch (e) {
      console.error("Login error:", e);
      res.status(500).json({ message: "Login error" });
    }
  });

  /* --- PASSWORD RESET --- */
  app.post("/forgot-password", async (req, res) => {
    const { email } = req.body;
    try {
      const user = await User.findOne({ email });
      if (!user) {
        // We still return true to avoid email enumeration attacks
        return res.json({ success: true, message: "If an account with that email exists, a password reset link has been sent." });
      }

      // Generate token
      const token = crypto.randomBytes(32).toString('hex');
      user.resetPasswordToken = token;
      user.resetPasswordExpires = Date.now() + 3600000; // 1 hour
      await user.save();

      // Send Email
      let transporter = nodemailer.createTransport({
        host: process.env.EMAIL_HOST || "smtp.ethereal.email",
        port: process.env.EMAIL_PORT || 587,
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS,
        },
      });

      // If no env config, use Ethereal for testing automatically
      if (!process.env.EMAIL_USER) {
        let testAccount = await nodemailer.createTestAccount();
        transporter = nodemailer.createTransport({
          host: "smtp.ethereal.email",
          port: 587,
          secure: false, // true for 465, false for other ports
          auth: {
            user: testAccount.user, // generated ethereal user
            pass: testAccount.pass, // generated ethereal password
          },
        });
      }

      const resetUrl = `http://localhost:3000/reset-password.html?token=${token}`;

      let info = await transporter.sendMail({
        from: '"InterviewCoach" <noreply@interviewcoach.com>',
        to: user.email,
        subject: "Password Reset Request",
        text: `You are receiving this because you (or someone else) have requested the reset of the password for your account.\n\n
          Please click on the following link, or paste this into your browser to complete the process:\n\n
          ${resetUrl}\n\n
          If you did not request this, please ignore this email and your password will remain unchanged.\n`,
        html: `<p>You requested a password reset</p><p>Click this <a href="${resetUrl}">link</a> to set a new password.</p>`
      });

      console.log("Password reset email sent: %s", info.messageId);
      // Log URL to terminal for easy testing with Ethereal
      if (nodemailer.getTestMessageUrl(info)) {
        console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
      }

      res.json({ success: true, message: "If an account with that email exists, a password reset link has been sent." });

    } catch (e) {
      console.error("Forgot Password Error:", e);
      res.status(500).json({ success: false, message: "Error processing request" });
    }
  });

  app.post("/reset-password", async (req, res) => {
    const { token, newPassword } = req.body;
    try {
      const user = await User.findOne({
        resetPasswordToken: token,
        resetPasswordExpires: { $gt: Date.now() }
      });

      if (!user) {
        return res.status(400).json({ success: false, message: "Password reset token is invalid or has expired." });
      }

      // Hash new password
      user.password = await bcrypt.hash(newPassword, 10);
      user.resetPasswordToken = undefined;
      user.resetPasswordExpires = undefined;
      await user.save();

      res.json({ success: true, message: "Your password has been changed successfully. You can now log in." });

    } catch (e) {
      console.error("Reset Password Error:", e);
      res.status(500).json({ success: false, message: "Error resetting password." });
    }
  });

  /* --- USER PROFILE MANAGEMENT --- */
  app.get("/user-profile/:email", verifyToken, async (req, res) => {
    try {
      const user = await User.findOne({ email: req.params.email }, "-password");
      if (!user) return res.status(404).json({ message: "User not found" });
      res.json(user);
    } catch (e) { res.status(500).json({ message: "Error fetching profile" }); }
  });

  app.put("/user-profile/:email", verifyToken, async (req, res) => {
    try {
      const { name, role, experienceLevel, github, linkedin, portfolio, phone } = req.body;
      const user = await User.findOneAndUpdate(
        { email: req.params.email },
        { name, role, experienceLevel, github, linkedin, portfolio, phone },
        { returnDocument: 'after' }
      );
      if (!user) return res.status(404).json({ message: "User not found" });
      res.json({ success: true, user: { name: user.name, email: user.email, role: user.role, experienceLevel: user.experienceLevel } });
    } catch (e) { res.status(500).json({ message: "Error updating profile" }); }
  });
} else {
  app.post("/register", (req, res) => res.status(503).json({ message: "DB unavailable" }));
  app.post("/login", (req, res) => res.status(503).json({ message: "DB unavailable" }));
}

/* --- RESUME UPLOAD --- */
if (multer) {
  const upload = multer({ dest: "uploads/", limits: { fileSize: 10 * 1024 * 1024 } });

  app.post("/upload-resume", verifyToken, upload.single("resume"), async (req, res) => {
    try {
      const { email } = req.body;
      const file = req.file;
      if (!file) return res.status(400).json({ message: "No file uploaded." });

      const text = await extractResumeText(file.path, file.mimetype);
      if (!text || text.length < 50) return res.status(400).json({ message: "Resume text too short." });

      const prompt = `
      Perform a deep analysis of this resume.
      Task:
      1. Extract a concise executive summary (3-4 sentences max).
      2. Identify the candidate's experience level (Entry, Mid, Senior, Lead).
      3. List exactly 5-8 key technical skills.
      4. Suggest 3 specific interview questions related to their projects or skills.
      5. Calculate a match score (0-100) for a general Software Engineer role.
      6. Provide a list of suitable jobs based on the content.
      7. Provide a list of skills they need to improve.

      RESUME CONTENT:
      ${text.substring(0, 4000)}

      Return JSON strictly:
      {
        "summary": "string",
        "level": "string",
        "skills": ["string", "string"],
        "questions": ["string", "string"],
        "score": number, 
        "suggestions": ["string", "string"],
        "suitable_jobs": ["string", "string"],
        "skills_to_improve": ["string", "string"]
      }`;

      const analysisRaw = await callAI(prompt, "System: Expert Technical Recruiter");

      // Ensure strict structure and defaults
      const analysis = {
        score: analysisRaw.score || 0,
        skills: Array.isArray(analysisRaw.skills) ? analysisRaw.skills : [],
        level: analysisRaw.level || "Unknown",
        summary: analysisRaw.summary || "Candidate profile analysis unavailable.",
        suggestions: Array.isArray(analysisRaw.suggestions) ? analysisRaw.suggestions : [],
        questions: Array.isArray(analysisRaw.questions) ? analysisRaw.questions : [],
        suitable_jobs: Array.isArray(analysisRaw.suitable_jobs) ? analysisRaw.suitable_jobs : [],
        skills_to_improve: Array.isArray(analysisRaw.skills_to_improve) ? analysisRaw.skills_to_improve : []
      };

      if (Resume && email) {
        await new Resume({
          userEmail: email,
          filename: file.originalname,
          extractedText: text,
          analysis: analysis
        }).save();
      }

      res.json({ success: true, analysis });
    } catch (error) {
      console.error("❌ Resume Upload Error:", error.message);
      res.status(400).json({ success: false, message: error.message || "Upload failed. Please ensure the file is valid." });
    }
  });
}

/* --- NEW FEATURES: Question Generator & Personality Analyzer --- */

app.post("/generate-questions", verifyToken, async (req, res) => {
  try {
    const { email, jobRole, jobDescription } = req.body;
    let contextData = `Target Role: ${jobRole || 'Software Engineer'}\n`;
    if (jobDescription) {
      contextData += `Job Description: ${jobDescription}\n`;
    }

    if (Resume) {
      const resume = await Resume.findOne({ userEmail: email }).sort({ uploadedAt: -1 });
      if (resume && resume.analysis) {
        contextData += `Candidate Skills: ${resume.analysis.skills.join(", ")}\n`;
        contextData += `Candidate Experience Level: ${resume.analysis.level}\n`;
      }
    }

    // Fetch previously generated questions to avoid repetition
    if (GeneratedQuestion) {
      const pastQs = await GeneratedQuestion.find({ userEmail: email }).sort({ timestamp: -1 }).limit(10);
      if (pastQs.length > 0) {
        contextData += `PREVIOUSLY ASKED QUESTIONS (DO NOT REPEAT THESE):\n`;
        pastQs.forEach((q, i) => {
          contextData += `${i + 1}. ${q.questionText}\n`;
        });
      }
    }

    const prompt = `
You are an expert technical interviewer. Generate 5 distinct, highly personalized interview questions for this specific candidate.

Context:
${contextData}

CRITICAL RULES:
1. STRICTLY TAILOR the questions to the "Target Role" and "Job Description". Do not ask general software engineering questions if a specific role like "Frontend" or "Data Scientist" is specified.
2. DO NOT ask generic questions like "Tell me about yourself" or "What are your strengths/weaknesses".
3. Provide a mix of technical, scenario-based, and behavioral questions specific to the role and candidate skills.
4. If "Candidate Skills" are provided, ensure at least 2 questions test those specific skills deeply.
5. Ensure these 5 questions are distinctly different from each other.

Task:
Return strictly a JSON object with a "questions" array containing 5 strings.
{
  "questions": ["q1", "q2", "q3", "q4", "q5"]
}`;

    const aiRes = await callAI(prompt);
    res.json({ success: true, questions: aiRes.questions || [] });
  } catch (error) {
    console.error("Generate Questions Error:", error);
    res.status(500).json({ success: false, message: "Error generating questions" });
  }
});

app.post("/analyze-personality", verifyToken, async (req, res) => {
  try {
    const { email, textInput } = req.body;
    if (!textInput || textInput.length < 20) {
      return res.status(400).json({ success: false, message: "Input text is too short. Please provide at least 20 characters." });
    }

    const prompt = `
Analyze this candidate's personality and communication style based on their response.
Candidate Input: "${textInput}"

Task:
1. Provide a brief summary of how they communicate.
2. Score these 4 traits from 0 to 100: Confidence, Clarity, Positivity, ProblemSolving.

Return strictly a JSON object:
{
  "summary": "Brief summary",
  "traits": {
    "Confidence": 85,
    "Clarity": 90,
    "Positivity": 80,
    "ProblemSolving": 75
  }
}`;

    const aiRes = await callAI(prompt);

    const analysis = {
      summary: aiRes.summary || "Analysis completed based on provided text.",
      traits: aiRes.traits || { Confidence: 70, Clarity: 70, Positivity: 70, ProblemSolving: 70 }
    };

    res.json({ success: true, analysis });
  } catch (error) {
    console.error("Personality Analyzer Error:", error);
    res.status(500).json({ success: false, message: "Error analyzing personality" });
  }
});

/* --- DYNAMIC DASHBOARD ANALYTICS --- */
app.get("/user-dashboard/:email", verifyToken, async (req, res) => {
  try {
    const { email } = req.params;

    // Fetch user for gamification stats
    const user = User ? await User.findOne({ email }) : null;
    const practiceStreak = user ? user.practiceStreak || 0 : 0;

    // 1. Resume Data
    const resumeDocs = Resume ? await Resume.find({ userEmail: email }).sort({ uploadedAt: -1 }) : [];
    const latestResumeDoc = resumeDocs.length > 0 ? resumeDocs[0] : null;

    // 2. Interview Performance Data
    // Get all attempts for this user
    const attempts = InterviewAttempt ? await InterviewAttempt.find({ userEmail: email }).sort({ timestamp: 1 }) : [];

    // --- Metrics Config ---
    const totalQuestions = attempts.length;

    // Avg Score
    const totalScore = attempts.reduce((sum, a) => sum + (a.score || 0), 0);
    const avgScore = totalQuestions > 0 ? (totalScore / totalQuestions).toFixed(1) : 0;

    // Practice Time (Actual seconds from DB)
    const practiceSecs = attempts.reduce((sum, a) => sum + (a.timeTaken || 0), 0);
    const pmins = Math.floor(practiceSecs / 60);
    const psecs = practiceSecs % 60;
    const practiceTime = pmins > 0 ? `${pmins}m ${psecs}s` : `${psecs}s`;

    // Gamification Logic
    let badge = "Beginner Interviewer";
    if (totalQuestions >= 50) badge = "Tech Guru";
    else if (totalQuestions >= 20) badge = "Rising Star";
    else if (totalQuestions >= 5) badge = "Active Learner";

    let nextGoal = "Score 50%";
    const currentAvg = parseFloat(avgScore);
    if (currentAvg >= 90) nextGoal = "Maintain 90%+";
    else if (currentAvg >= 80) nextGoal = "Score 85%";
    else if (currentAvg >= 70) nextGoal = "Score 80%";
    else if (currentAvg >= 50) nextGoal = "Score 70%";
    else if (totalQuestions > 0) nextGoal = "Score 60%";

    // --- Charts Logic ---

    // 1. Skill Distribution (Donut Chart)
    const skillCounts = { Technical: 0, Behavioral: 0, SystemDesign: 0 };
    attempts.forEach(a => {
      // Simple fuzzy match or fallback
      const cat = a.category || "Technical";
      if (cat.match(/Behavioral/i)) skillCounts.Behavioral++;
      else if (cat.match(/System/i)) skillCounts.SystemDesign++;
      else skillCounts.Technical++;
    });

    // 2. Performance Trend (Line Chart - Last 7 entries or days)
    // We'll group by "Session" (just take the last 10 attempts for simplicity in this demo)
    const recentAttempts = attempts.slice(-10);
    const trendLabels = recentAttempts.map(a => new Date(a.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }));
    const trendData = recentAttempts.map(a => a.score);

    res.json({
      resume: latestResumeDoc ? latestResumeDoc.analysis : null,
      stats: {
        totalQuestions,
        avgScore,
        practiceTime,
        practiceStreak,
        badge,
        nextGoal
      },
      charts: {
        skills: [skillCounts.Technical, skillCounts.Behavioral, skillCounts.SystemDesign],
        trendLabels,
        trendData
      }
    });

  } catch (e) {
    console.error("Dashboard Error:", e);
    res.status(500).json({ message: "Server Error" });
  }
});

app.get("/interview-history/:email", verifyToken, async (req, res) => {
  try {
    const { email } = req.params;
    const history = InterviewAttempt ? await InterviewAttempt.find({ userEmail: email }).sort({ timestamp: -1 }) : [];
    res.json({ success: true, history });
  } catch (e) { res.status(500).json({ success: false, message: e.message }); }
});

app.get("/resume-history/:email", verifyToken, async (req, res) => {
  try {
    const { email } = req.params;
    const resumes = Resume ? await Resume.find({ userEmail: email }).sort({ uploadedAt: -1 }) : [];
    res.json({ success: true, resumes });
  } catch (e) { res.status(500).json({ success: false, message: e.message }); }
});

/* --- INTERVIEW CHAT (Saving Attempts via WebSockets) --- */
if (io) {
  io.use((socket, next) => {
    if (!jwt) return next();
    const token = socket.handshake.auth.token;
    if (!token) return next(new Error("Authentication error"));
    jwt.verify(token, process.env.JWT_SECRET || "supersecretjwtkey", (err, decoded) => {
      if (err) return next(new Error("Authentication error"));
      socket.user = decoded;
      next();
    });
  });

  io.on("connection", (socket) => {
    console.log("🟢 WebSocket Connected:", socket.id);

    socket.on("chatMessage", async (data) => {
      const { email, message, context, isFirst, timeTaken } = data;

      try {
        let user = User ? await User.findOne({ email }) : null;
        let resumeData = null;
        if (context.mode === 'resume' && Resume) {
          const resume = await Resume.findOne({ userEmail: email });
          resumeData = resume ? resume.analysis : null;
        }

        // 1. Evaluate User Answer
        let evaluation = null;
        if (!isFirst) {
          // Get the last generated question for this user to store it in the attempt
          const lastQ = GeneratedQuestion ? await GeneratedQuestion.findOne({ userEmail: email }).sort({ timestamp: -1 }) : null;
          const questionText = lastQ ? lastQ.questionText : "Interview Question";

          // Strict JSON prompt for evaluation
          const evalPrompt = `
evaluate this answer

Question: "${questionText}"

User Answer: 
"${message}"

Instructions for deep evaluation:
1. Semantic Analysis: Read the candidate's answer carefully. Analyze its length, technical correctness, keywords, and reasoning (because, therefore, for example).
2. Forced Reasoning: Before scoring, formulate a short internal reasoning explaining your thoughts on the specific content of the answer.
3. Scoring (0-10): Be realistic. Detailed correct answers with examples deserve 8-10. Short but correct answers deserve 5-7. Vague or incorrect answers deserve 0-4.
4. Dynamic Feedback: Create completely unique feedback that references specific words or concepts from the candidate's answer.
5. PROHIBITED: Do not return generic, hardcoded, repetitive text. Your response must change when the answer changes.

Return STRICT JSON only:
{
  "reasoning": "brief internal analysis of the exact answer content",
  "score": number,
  "feedback": "unique, specific feedback citing the actual answer",
  "category": "Technical"
}
`;

          try {
            console.log("➡️ Sending evaluation prompt to AI...");
            const rawEval = await callAI(evalPrompt);
            evaluation = {
              score: (rawEval && typeof rawEval.score === 'number') ? rawEval.score : 5,
              feedback: (rawEval && rawEval.feedback && !rawEval.feedback.includes("Your answer provides no detail"))
                ? rawEval.feedback
                : `I read your response starting with "${message.substring(0, 20)}...", but you need to elaborate with more technical details and specific examples.`,
              category: (rawEval && rawEval.category) ? rawEval.category : "Technical"
            };
            console.log("✅ Evaluation completed successfully by AI.");
          } catch (err) {
            console.error("🚨 Evaluation Error Caught in Server.js:", err.message);
            evaluation = {
              score: 3,
              feedback: `Evaluation failed for your answer. Our AI is currently unavailable or unable to parse response: "${message.substring(0, 20)}...". Please try again.`,
              category: "Technical"
            };
          }

          // SAVE ATTEMPT
          if (evaluation && InterviewAttempt) {
            await new InterviewAttempt({
              userEmail: email,
              question: questionText,
              userAnswer: message,
              aiFeedback: evaluation.feedback,
              score: evaluation.score,
              timeTaken: timeTaken || 0,
              category: evaluation.category || "Technical",
              sessionMode: context.mode
            }).save();

            // Gamification Streak Logic (Requires 3 mins / 180s per day)
            if (user && InterviewAttempt) {
              const today = new Date();
              today.setHours(0, 0, 0, 0);

              const tomorrow = new Date(today);
              tomorrow.setDate(tomorrow.getDate() + 1);

              // Sum user's practice time for today
              const todaysAttempts = await InterviewAttempt.find({
                userEmail: email,
                timestamp: { $gte: today, $lt: tomorrow }
              });

              const todaysPracticeSecs = todaysAttempts.reduce((sum, a) => sum + (a.timeTaken || 0), 0);

              if (todaysPracticeSecs >= 180) {
                if (!user.lastPracticeDate) {
                  user.practiceStreak = 1;
                  user.lastPracticeDate = today;
                } else {
                  const lastDate = new Date(user.lastPracticeDate);
                  lastDate.setHours(0, 0, 0, 0);

                  const diffTime = Math.abs(today - lastDate);
                  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

                  if (diffDays === 1) {
                    user.practiceStreak = (user.practiceStreak || 0) + 1;
                    user.lastPracticeDate = today;
                  } else if (diffDays > 1) {
                    user.practiceStreak = 1;
                    user.lastPracticeDate = today;
                  }
                  // If diffDays === 0, they already got their streak for today.
                }
                await user.save();
              }
            }
          }
        }
        // 2. PRACTICE MODE QUESTION LIMIT CHECK

        if(context.mode === "practice" && context.questionNumber >= context.questionLimit){
    
           socket.emit("chatResponse",{
             reply: "✅ Practice session completed! You answered all questions.",
             evaluation
            });

            return;
        }



        // 2. Generate Next Question
        let contextData = "";
        if (context.mode === 'resume' && resumeData) {
          contextData = `
            Candidate Resume Analysis:
            - Level: ${resumeData.level}
            - Detected Skills: ${resumeData.skills.join(", ")}
            - Summary: ${resumeData.summary || "N/A"}

            Task: Ask a relevant technical or behavioral interview question tailored to this candidate's profile.
              `;
        } else {
          contextData = `
            Job Role: ${user ? user.role : 'Software Engineer'}
            Experience Level: ${user ? user.experienceLevel : 'Entry'}
            Topic: ${context.topic || context.skill || 'General Software Engineering'}
            Mode: ${context.mode}
          `;
        }

        if (GeneratedQuestion) {
          const pastQs = await GeneratedQuestion.find({ userEmail: email, sessionMode: context.mode }).sort({ timestamp: -1 }).limit(10);
          if (pastQs.length > 0) {
            contextData += `\nPREVIOUSLY ASKED QUESTIONS (DO NOT ASK THESE AGAIN):\n`;
            pastQs.forEach((q, i) => {
              contextData += `${i + 1}. ${q.questionText}\n`;
            });
          }
        }

        const nextQPrompt = `
            const nextQPrompt = `
            Generate the next interview question.

            Mode: ${context.mode}

            Context:
            ${contextData}

            Rules:
            1. If mode = practice, ask short topic based questions.
            2. If mode = interview, ask deep scenario based questions.
            3. Focus on topic: ${context.topic || "software engineering"}.
            4. Do not repeat previous questions.

            Previous Interaction:
            User Answer: "${message}"
            AI Feedback: ${JSON.stringify(evaluation)}

            Return strictly JSON:

            {
            "message": "next question"
            }
`           ;
        const nextQ = await callAI(nextQPrompt);

        // SAVE THE NEWLY GENERATED QUESTION
        if (nextQ && nextQ.message && GeneratedQuestion) {
          await new GeneratedQuestion({
            userEmail: email,
            questionText: nextQ.message,
            category: evaluation ? evaluation.category : "Technical",
            sessionMode: context.mode
          }).save();
        }

        socket.emit("chatResponse", {
          reply: nextQ.message,
          evaluation
        });

      } catch (error) {
        console.error("Chat Error:", error);
        socket.emit("chatError", { message: "Chat Logic Failed" });
      }
    });

    socket.on("disconnect", () => {
      console.log("🔴 WebSocket Disconnected:", socket.id);
    });
  });
}

// Start Server
server.listen(PORT, () => console.log(`🚀 Server running on http://localhost:${PORT}`));